services: 
  
  db:
    image: postgres:17-alpine
    container_name: ${DB_NAME}-container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microcredito-network

  backend:

    build:
      context: .
      dockerfile: Dockerfile
    container_name: microcreditos_app-container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - microcredito-network

networks:
  microcredito-network:
    driver: bridge
   
volumes:
  pgdata:



