spring.application.name=apimicrocreditos
spring.jpa.open-in-view=false

#configurations jpa/hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.org.hibernate.orm.jdbc.bind=INFO
server.error.include-stacktrace=never


#flyway
spring.flyway.enabled=false

#jwt
security.jwt.secret-key=${JWT_KEY}
security.jwt.expiration=5m

#refresh token
security.refresh-token.expiration=7d
security.refresh-token.grace-period=5s

#jobs
security.refresh-token.cleanup-cron=0 0 3 * * *