
CREATE TABLE users (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
public_id UUID NOT NULL UNIQUE,
name TEXT NOT NULL,
last_name TEXT NOT NULL,
username TEXT NOT NULL UNIQUE,
password_hash TEXT NOT NULL,
email TEXT NOT NULL UNIQUE,
is_identity_verified BOOLEAN DEFAULT FALSE NOT NULL,
birth_date DATE NOT NULL,
created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
last_update TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE roles (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
CONSTRAINT chk_valid_role
CHECK (name in ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE user_roles (
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
PRIMARY KEY (user_id, role_id)
);

CREATE TABLE refresh_tokens(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
public_id UUID NOT NULL UNIQUE,
token TEXT NOT NULL UNIQUE,
user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
status TEXT NOT NULL,
rotated_at TIMESTAMPTZ,
expires_at TIMESTAMPTZ NOT NULL,
created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
last_update TIMESTAMPTZ DEFAULT now() NOT NULL,
CONSTRAINT chk_valid_status
CHECK (status in ('ACTIVE', 'ROTATED','REVOKED'))
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

INSERT INTO roles (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');