name: push_validation

on: [push]

jobs:

  validate-tests:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Copy code
        uses: actions/checkout@v4
      
      - name: Configure Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
    
      - name: Run tests
        run: mvn test
        env:
          POSTGRES_URL: ${{ secrets.DB_URL }}
          POSTGRES_NAME: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
