name: push_validation

on:
  push:
    branches: [main]
  pull_request:

jobs:

  validate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test
        run: ./mvnw --batch-mode verify

  build-image:
    runs-on: ubuntu-latest
    needs: validate-tests
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t apimicrocreditos:${{ github.sha }} .